### PR TITLE
Implement tab pooling

### PR DESCRIPTION
**Pull request by jkob**
This PR implements #3 

Please comment if there's anything you want me to add or change.

## Changes

- Now launches Chrome as soon as `src/core/pdf-core.js` is "loaded".

- function `render` now dynamically gets the tab it's gonna do the rendering work on. Either by using a unused tab, or by creating a new tab. (As opposed to creating launching a Chrome instance and creating a new tab each time)

- At the end of `render`, it now toggles the availability of that tab. (available: false => available: true)

## Added

- Added a `.env` option: `MAX_POOL_SIZE`. Sets the limit for how many tabs may be in an array.

- Added functions:
	* pool_getConnection
	* pool_addConnection
	* pool_toggleAvailability

## What might be added:

- Moving pooling functionality into seperate file
- Tests

### CODE REVIEW

**Comment by Kikobeats** [comment]
woah, awesome PR!

One suggestion, Did you do any benchmark for know how this improve the current codebase?

I think could be easy to do it and reports a useful metric for know what's the ideal pool size.

**Comment by jkob** [comment]
@Kikobeats No I did not do any benchmarks. I've never done any kind of benchmarking tests before, but feel free to contribute if you wish.

**Comment by jkob** [comment]
Also, I've been thinking about moving this functionality out of the file as I feel like modularity is always good. @kimmobrunfeldt is this something you want me to do?

**Comment by kimmobrunfeldt** [comment]
Thanks for the effort. I'd like to have a more generic pooling module in the code base. E.g. https://github.com/coopernurse/node-pool. The coding style is also not in match with the eslint rules (`npm run lint`). Those would need to be fixed. 

I also might be taking a stab at the pooling issue later. It needs to be carefully implemented so that render requests are not accidentally leaked to incorrect responses.

**Comment by kimmobrunfeldt** [comment]
Closing due to inactivity. It wasn't merged because of the above reasons.

**Pull request closed without merging**
